version: '3.8'
services:
  arma3:
    build: .
    image: ghcr.io/brettmayson/arma3server/arma3server:v2
    platform: linux/amd64
    container_name: arma3
    network_mode: host
    volumes:
      - './configs:/arma3/server/configs'
      - './mods:/arma3/server/mods'
      - './servermods:/arma3/server/servermods'
      - './server:/arma3/server/'
    env_file: .env
    restart: unless-stopped
