services:
  arma3:
    build: .
    platform: linux/amd64
    container_name: arma3
    ports:
      - ${HOST_IP}:2302:2302/udp
      - ${HOST_IP}:2303:2303/udp
      - ${HOST_IP}:2304:2304/udp
      - ${HOST_IP}:2305:2305/udp
    volumes:
      - './configs:/arma3/server/configs'
      - './mods:/arma3/server/mods'
      - './servermods:/arma3/server/servermods'
      - './server:/arma3/server/'
      - './cache:/arma3/cache'
    env_file: .env
    restart: unless-stopped
